### PR TITLE
Leveling Mode

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
UIC support for https://github.com/RealDeviceMap/RealDeviceMap/pull/28

## How Has This Been Tested?
Tested locally with GDS beta version

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by bushe** [comment]
Ran this PR with the associated RDM PR for ~12 hours, everything appears to work will but I needed to remove the .xcfilelists from https://github.com/RealDeviceMap/RealDeviceMap-UIControl/blob/c880adaca60e3c52f56f91b86e36e554a2587b21/RealDeviceMap-UIControl.xcodeproj/project.pbxproj#L256 and https://github.com/RealDeviceMap/RealDeviceMap-UIControl/blob/c880adaca60e3c52f56f91b86e36e554a2587b21/RealDeviceMap-UIControl.xcodeproj/project.pbxproj#L260

**Review by SkOODaT — DISMISSED** [review]
seems to work fine, as long as you have all the startup loc's the same ie UIC, RDM and In IPA, would be nice to be able to see spin counts still to have an idea how many in a day its chewed

**Review by Gladiator10864 — DISMISSED** [review]
It's been working well for the past few days now. But I've had trouble determining exact 0-30 times I'm getting because a lot of my accounts are already partially leveled by other means.

**Review by DavisPoGo — DISMISSED** [review]
Been running fine for over a week

**Comment by samonthenetuk** [comment]
Since latest Pokemon GO update devices keep getting stuck on the AR welcome screen when it accidentally presses on a Pokemon and this does not resolve itself. You have to physically intervene. Other than this the feature works well.

**Comment by ARGG1** [comment]
Merging this to master - causes device (Iphone SE) to tap new player button, instead of returning player. I have not been able to proceed further.

**Comment by n0varino** [comment]
tested this for a few days now - leveling itself is working fine, but as ARGG1 mentioned the devices have problems switching accounts.

**Pull request merged**
